### PR TITLE
some fixes to jube runner and an install script

### PR DESCRIPTION
**Pull request by chanokin**
I modified the way paths are generated/stored in the JUBE_runner helper file and added an install script to solve the JUBE and sdict dependencies.

### CODE REVIEW

**Comment by chanokin** [comment]
Do you still have any dependencies on pypet? I believe most of the list I added were there for the latter.

Also, do you need deap or is that an old dependency as well?

**Comment by sdiazpier** [comment]
There should be no more dependencies to pypet left. Deap is still used by the genetic algorithm optimizer.

**Comment by chanokin** [comment]
So I reverted the reverted the requirements.txt file to the one you had before and removed the sdict dependency from the install script as it was copied into l2l/__init__.py . Also, I think the Paths object could be used to define many of the jube_runner paths.

**Comment by sdiazpier** [comment]
Dear @chanokin thanks for all the fixes. It looks ok for me now.

**Pull request merged**
